### ISSUE TITLE
BBBC022 on s3://cytodata cannot be downloaded

### ISSUE THREAD

**Issue by tilenkranjc** [cytodata/cytodata-hackathon-2018#11]
I'm trying to copy the BBBC022 profiles from cytodata s3 bucket to set up a benchmark pipeline for our cell painting method development. I can list the files in the bucket, but cannot copy or sync anything. Could you please change the permissions accordingly?
 Thanks.

**Comment by ErinWeisbart** [comment]
@tilenkranjc Sorry for the inconvenience. I am in the process of getting all of the cytodata datasets moved over to the [cellpainting-gallery](https://github.com/broadinstitute/cellpainting-gallery/). Once that is complete, you'll be able to access BBBC022 there as cpg0030-gustafsdottir-cellpainting.

In the meantime, there are many other Cell Painting datasets already available in the cellpainting-gallery that you might be able to use instead?

@shntnu I too can only `ls` cytodata so I need your help to fix permissions before I can complete the transfer of Bioactives-BBBC022-Gustafsdottir (cpg0030-gustafsdottir-cellpainting) and LUAD-BBBC043-Caicedo (cpg0031-caicedo-cmvip).

**Comment by tilenkranjc** [comment]
Thanks for the info. Yeah, happy to wait for the data to be transferred. 

Meanwhile, I used the original features from the bbbc website. BBBC022 is kind of convenient dataset for benchmarking, that's why it'd be great to have the processed features data.

**Comment by ErinWeisbart** [comment]
@tilenkranjc The data has been transferred to [cellpainting-gallery](https://github.com/broadinstitute/cellpainting-gallery/) as `cpg0030-gustafsdottir-cellpainting`.

Please feel free to ask questions in that repo if you have any trouble accessing the files.
